### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Boscop** [dyule/wamp-rs#4]
https://github.com/dyule/wamp-rs/search?utf8=%E2%9C%93&q=Recieved&type=
https://github.com/dyule/wamp-rs/search?utf8=%E2%9C%93&q=goobye&type=
https://github.com/dyule/wamp-rs/blob/master/src/client.rs#L391

**Comment by dyule** [comment]
I think I have a problem with that word.  I have never been able to spell it right in my entire life.
