### ISSUE TITLE
Client connection being closed

### ISSUE THREAD

**Issue by crackcomm** [dyule/wamp-rs#6]
I have [client](https://github.com/dyule/wamp-rs/blob/master/examples/pubsubclient.rs) connected to server and it sometimes reads for seconds sometimes minutes, then it disconnect's with a message:

```
DEBUG:wamp::client: Result of connection: Ok(())
```

Reading stops, writes are resulting in error.

```
DEBUG:wamp::client: Sending message Publish(2, PublishOptions { acknowledge: true }, URI { uri: "test" }, Some([]), None) via wamp.2.msgpack
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: WSError(WS Error <Queue(Disconnected)>) }', /checkout/src/libcore/result.rs:859
```

Browser haven't had a single connection problem with this server for hours.

I am going to investigate this further tomorrow but maybe someone knows about this issue and what could be causing it.

The client connects over SSL using OpenSSL.

**Comment by crackcomm** [comment]
It even gave me:

```
INFO:pubsubclient: Connecting
TRACE:wamp::client: Beginning Connection
TRACE:wamp::client: Got sender
DEBUG:wamp::client: Result of connection: Ok(())
```

While the same client was connected in another terminal.

I also tested with two clients connected and one disconnected while other is still connected.

**Comment by dyule** [comment]
Hi @crackcomm.  Are you using the crates.io version of wamp-rs?  If so, there's an underlying mio issue that seems to cause problems on windows.  Using the github version of this crate may fix your issue.

**Comment by crackcomm** [comment]
I cloned `wamp-rs` from github.

I set `ws=trace` and this is what I've got:

```
DEBUG:wamp::client: Processing message from server (state: Connected)
DEBUG:wamp::client: Recieved a message from the server: Event(correct event here)
TRACE:ws::frame: Position in buffer 1003
TRACE:ws::io: Scheduling connection to 123.123.123.123:443 as Ready {Readable}
TRACE:ws::io: Active connections 1
TRACE:ws::io: Waiting for event
ERROR:ws::io: Websocket shutting down for interrupt.
TRACE:ws::io: Processing 0 events
TRACE:ws::io: Active connections 1
DEBUG:wamp::client: Result of connection: Ok(())
```

**Comment by crackcomm** [comment]
As @Boscop mentioned in #5 it works now, I will close this issue if it'll pass 24h test.

**Comment by crackcomm** [comment]
It's fixed with latest `ws-rs`.
